// Banderas (emoji) para los equipos del calendario del Mundial 2026.
// Si un equipo no esta en el mapa (p.ej. "Por definir..."), se usa un balon.
const FLAGS: Record<string, string> = {
  España: "🇪🇸",
  "Cabo Verde": "🇨🇻",
  Bélgica: "🇧🇪",
  Egipto: "🇪🇬",
  "Arabia Saudita": "🇸🇦",
  Uruguay: "🇺🇾",
  Irán: "🇮🇷",
  "Nueva Zelanda": "🇳🇿",
  Francia: "🇫🇷",
  Senegal: "🇸🇳",
  Irak: "🇮🇶",
  Noruega: "🇳🇴",
  Argentina: "🇦🇷",
  Argelia: "🇩🇿",
  Portugal: "🇵🇹",
  "RD Congo": "🇨🇩",
  Inglaterra: "🏴",
  Croacia: "🇭🇷",
  Ghana: "🇬🇭",
  Panamá: "🇵🇦",
  Uzbekistán: "🇺🇿",
  Colombia: "🇨🇴",
  Chequia: "🇨🇿",
  Sudáfrica: "🇿🇦",
  Suiza: "🇨🇭",
  "Bosnia y Herzegovina": "🇧🇦",
  Canadá: "🇨🇦",
  Catar: "🇶🇦",
  México: "🇲🇽",
  "Corea del Sur": "🇰🇷",
  "Estados Unidos": "🇺🇸",
  Australia: "🇦🇺",
  Escocia: "🏴",
  Marruecos: "🇲🇦",
  Brasil: "🇧🇷",
  Haití: "🇭🇹",
  "Países Bajos": "🇳🇱",
  Suecia: "🇸🇪",
  Alemania: "🇩🇪",
  "Costa de Marfil": "🇨🇮",
  Ecuador: "🇪🇨",
  Curazao: "🇨🇼",
  Paraguay: "🇵🇾",
  "Japón": "🇯🇵",
  "Túnez": "🇹🇳",
  Austria: "🇦🇹",
  Jordania: "🇯🇴",
  Noruega: "🇳🇴",
  Argelia: "🇩🇿",
};

export function flagEmoji(team: string): string {
  return FLAGS[team] || "⚽";
}
